source 'https://rubygems.org'
gem 'aws-sdk', '~> 1.48.1'
gem 'uuid', '~> 2.3.7'
gem 'sinatra'
gem 'ruby_odata'
gem 'padrino-helpers'
gem 'haml'
gem 'rack-cache'
gem 'haml'
gem 'chartkick'
gem 'json'
gem 'mail'
gem 'pony'